"""
NPC Conversation Handler - 3-Layer Architecture

Layer 1: Intent detection and entity extraction (rule-based)
Layer 2: ConversationSimulator - game state simulation (packets only)
Layer 3: NPCResponseGenerator - natural language response generation

This module orchestrates the three layers without mixing concerns.
"""

import asyncio
import json
import os
import re

from server.state import (
    get_npc_data, get_player_state,
    _items_db, player_sessions, socketio,
    conversation_memories, intent_detector, response_generator
)
from engine.conversation_simulator import simulate_conversation, process_heal
from engine.world_simulator import simulate_world
from engine.conversation_state_manager import get_or_create_state, Mode, Substate


def handle_npc_conversation(npc_id, player_text, player_id):
    """Handle NPC conversation using 3-layer system.
    
    Args:
        npc_id: The internal npc ID (e.g. "grim"), not the display name.
        player_text: The player's message.
        player_id: The player's ID.
    
    Returns:
        str: NPC response text (generated by Layer 3)
    """
    npc_data = get_npc_data(npc_id)
    if not npc_data:
        return f"That person doesn't seem to be here."

    # Get player state
    state = get_player_state(player_id)
    if state is None:
        return "You seem lost in thought."

    conversation = npc_data.get('conversation', {})
    npc_name = npc_data.get('name', npc_id)
    greeting = conversation.get('greeting', f"Hello, I'm {npc_name}.")
    farewell_msg = conversation.get('farewell', f"{npc_name} nods and returns to his work.")
    npc_personality = conversation.get('personality', 'friendly')

    player_lower = player_text.lower().strip()

    # Get NPC data for all layers
    shop_data = npc_data.get('shop') or {}
    world_data = npc_data.get('world') or {}
    world_shop = world_data.get('shop') or {}
    shop_items = world_shop.get('items', [])
    world_quests = world_data.get('available_quests', [])
    knowledge = npc_data.get('knowledge', {})
    
    # Extract topic/item/quest lists for Layer 1
    knowledge_topics = list(knowledge.keys()) if knowledge else []
    quest_ids = [q.get('id', '') for q in world_quests] if world_quests else []
    quest_names = [q.get('name', '') for q in world_quests] if world_quests else []
    shop_item_names = [item.get('name', item.get('item_name', '')) for item in shop_items] if shop_items else []
    
    # =========================================================
    # STRICT PIPELINE: Layer 1 → Layer 2 → Layer 3
    # =========================================================
    
    # Get conversation memory
    conversation_memory = conversation_memories.get(player_id, {}).get(npc_id, {
        'history': [], 'state': 'general', 'childish_warnings': 0
    })
    history = conversation_memory.get('history', [])
    
    # Extract NPC capabilities
    npc_capabilities = {
        "Information": {
            "ask_npc": True,
            "ask_location": True,
            "ask_creature": True,
            "ask_item": True,
            "ask_technique": True,
            "ask_shop": True,
            "ask_quest": True,
            "ask_history": True,
            "ask_rumor": True,
            "ask_world": True
        },
        "Quest": {
            "quest_interest": bool(world_quests),
            "quest_information": bool(world_quests),
            "quest_accept": bool(world_quests),
            "quest_decline": bool(world_quests),
            "quest_progress": False,
            "quest_completion": False,
            "quest_finish": bool(world_quests),
            "quest_clarification": bool(world_quests)
        },
        "Commerce": {
            "shop_interest": bool(shop_items),
            "shop_information": bool(shop_items),
            "browse_shop": bool(shop_items),
            "ask_price": bool(shop_items),
            "buy_item": bool(shop_items),
            "sell_item": False,
            "confirm_purchase": bool(shop_items)
        },
        "Training": {
            "training_interest": bool(npc_data.get('skills')),
            "learn_technique": bool(npc_data.get('skills')),
            "improve_technique": bool(npc_data.get('skills')),
            "ask_requirements": bool(npc_data.get('skills'))
        },
        "Services": {
            "heal_request": npc_data.get('type') == 'priest',
            "buff_request": npc_data.get('type') == 'priest',
            "repair_request": npc_data.get('type') == 'blacksmith',
            "identify_request": False,
            "appraisal_request": npc_data.get('type') == 'blacksmith',
            "transport_request": False,
            "lodging_request": False
        }
    }
    
    # =========================================================
    # LAYER 1: LLM Understanding (NO FALLBACKS)
    # =========================================================
    loop = None
    try:
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        layer1_result = loop.run_until_complete(
            intent_detector.understand(
                player_message=player_text,
                full_conversation=history,
                npc_capabilities=npc_capabilities,
                npc_knowledge_topics=knowledge_topics,
                npc_quest_ids=quest_ids,
                npc_quest_names=quest_names,
                npc_shop_items=shop_item_names
            )
        )
    except Exception as e:
        # Layer 1 failed - stop processing, raise error
        raise RuntimeError(f"Layer 1 (LLM Understanding) failed: {str(e)}")
    finally:
        if loop:
            loop.close()
    
    # =========================================================
    # STRICT PIPELINE LOGGING
    # =========================================================
    
    # Log Layer 1 raw output
    print("\n" + "="*80)
    print("=== LAYER 1 RAW ===")
    print("="*80)
    print(json.dumps(layer1_result, indent=2))
    print("="*80 + "\n")
    
    # =========================================================
    # LAYER 2: World Simulation (PASS-THROUGH ONLY)
    # =========================================================
    try:
        # Build input for world simulator - pass Layer 1 output unchanged
        world_state = {
            'tick_number': 0,
            'time_of_day': 'day'
        }
        
        simulation_input = {
            'player_message': player_text,
            'conversation_history': history,
            'conversation_memory': conversation_memory,
            'npc_data': npc_data,
            'player_state': state,
            'world_state': world_state,
            'layer1_understanding': layer1_result  # PASSED UNCHANGED - includes subject
        }
        
        # Log what we're sending to Layer 2
        print("\n" + "="*80)
        print("=== SENT TO LAYER 2 ===")
        print("="*80)
        print(json.dumps(simulation_input, indent=2, default=str))
        print("="*80 + "\n")
        
        # Run world simulation
        simulation_result = simulate_world(simulation_input)
        
        # Log Layer 2 output
        print("\n" + "="*80)
        print("=== LAYER 2 OUTPUT ===")
        print("="*80)
        print(json.dumps(simulation_result, indent=2, default=str))
        print("="*80 + "\n")
    except Exception as e:
        # Layer 2 failed - stop processing
        raise RuntimeError(f"Layer 2 (World Simulation) failed: {str(e)}")
    
    # Apply world actions from simulation
    _apply_world_actions(simulation_result.get('world_actions', []), state, player_id, npc_data)
    
    # Apply memory updates from simulation (including pending_purchase)
    _apply_memory_updates(simulation_result.get('memory_updates', {}), player_id, npc_id, 
                         conversation_memory, player_text)
    
    # Build packet for Layer 3 - pass Layer 2 output unchanged
    simulation_packet = simulation_result.copy()
    simulation_packet['npc_name'] = npc_name
    simulation_packet['npc_job'] = world_data.get('job', '')
    
    # =========================================================
    # LAYER 3: Response Generation (PASS-THROUGH ONLY)
    # =========================================================
    try:
        # Log what we're sending to Layer 3
        print("\n" + "="*80)
        print("=== SENT TO LAYER 3 ===")
        print("="*80)
        print(json.dumps(simulation_packet, indent=2, default=str))
        print("="*80 + "\n")
        
        # Generate response - pass packet unchanged
        loop = None
        try:
            loop = asyncio.new_event_loop()
            asyncio.set_event_loop(loop)
            response = loop.run_until_complete(
                response_generator.generate_response(
                    npc=npc_data,
                    player_message=player_text,
                    intent=layer1_result.get('primary_intent', 'general_chat'),
                    packet=simulation_packet,  # PASSED UNCHANGED
                    conversation_history=conversation_memory.get('history', []),
                    reasoning_context=simulation_result  # PASSED UNCHANGED
                )
            )
        finally:
            if loop:
                loop.close()
        
        # Log Layer 3 output
        print("\n" + "="*80)
        print("=== LAYER 3 OUTPUT ===")
        print("="*80)
        print(f"'{response}'")
        print("="*80 + "\n")
        
        # Store NPC response in conversation history
        _append_to_history(player_id, npc_id, player_text, response)
        
        return response
    except Exception as e:
        # Layer 3 failed - stop processing
        raise RuntimeError(f"Layer 3 (Response Generation) failed: {str(e)}")


def _determine_packet_action(simulation_result: Dict) -> str:
    """Determine the packet action from simulation result."""
    world_actions = simulation_result.get('world_actions', [])
    
    if not world_actions:
        # Default action based on conversation state
        conv_state = simulation_result.get('conversation_state', {})
        mode = conv_state.get('mode', 'general')
        
        action_map = {
            'greeting': 'greeting',
            'farewell': 'farewell',
            'quest': 'quest_list_available',
            'shop': 'shop_browse',
            'service': 'service_request',
            'information': 'share_information',
            'conversation': 'general_chat',
            'general': 'general_chat'
        }
        
        return action_map.get(mode, 'general_chat')
    
    # Use the first world action
    first_action = world_actions[0].get('type', 'general_chat')
    
    # Map world actions to packet actions
    # CRITICAL: Only actual success actions map to success packets
    action_map = {
        'offer_quest': 'offer_quest',
        'prepare_quest_offer': 'quest_list_available',
        'complete_purchase': 'shop_purchase_success',  # Only this means success
        'prepare_purchase': 'shop_offer_purchase',      # This is just an offer
        'prepare_service': 'service_request'
    }
    
    return action_map.get(first_action, 'general_chat')


def _apply_world_actions(world_actions: List[Dict], player_state: Dict, player_id: str, npc_data: Dict):
    """Apply world actions from simulation.
    
    CRITICAL: Only apply actions that represent ACTUAL COMPLETION.
    - complete_purchase: Apply (coins deducted, item added)
    - prepare_purchase: DO NOT apply (just an offer, not executed yet)
    - offer_quest: Apply (quest added to player)
    - quest_complete: Apply (quest moved to completed)
    """
    print(f"[WORLD_ACTIONS] Applying {len(world_actions)} world actions")
    for action in world_actions:
        action_type = action.get('type', '')
        print(f"[WORLD_ACTIONS] Processing action: {action_type}")
        
        if action_type == 'offer_quest':
            quest_id = action.get('quest_id')
            quest_name = action.get('quest_name', 'Unknown Quest')
            if quest_id:
                # Add quest to player's active quests (avoid duplicates)
                quests = player_state.setdefault('quests', [])
                # Check if quest already exists
                if not any(q.get('id') == quest_id for q in quests):
                    quests.append({
                        'id': quest_id,
                        'name': quest_name,
                        'status': 'active',
                        'steps': []
                    })
        
        elif action_type == 'quest_complete':
            quest_id = action.get('quest_id')
            if quest_id:
                # Move quest from active to completed
                active_quests = player_state.get('quests', [])
                completed_quests = player_state.setdefault('completed_quests', [])
                
                # Find and remove from active
                quest_to_complete = None
                for q in active_quests:
                    if q.get('id') == quest_id:
                        quest_to_complete = q
                        break
                
                if quest_to_complete:
                    active_quests.remove(quest_to_complete)
                    # Add to completed
                    completed_quests.append({
                        'id': quest_id,
                        'name': quest_to_complete.get('name', quest_id),
                        'completed_at': 'now'
                    })
                    
                    # Grant rewards from quest definition
                    quest_def = None
                    for npc in get_npc_data('grim') or {}:  # This won't work, need to load quest def
                        pass
                    
                    # Load quest definition to get rewards
                    quests_dir = os.path.join('data', 'quests')
                    quest_file = os.path.join(quests_dir, f'{quest_id}.json')
                    if os.path.exists(quest_file):
                        with open(quest_file, 'r') as f:
                            quest_def = json.load(f)
                    
                    if quest_def:
                        rewards = quest_def.get('rewards', {})
                        
                        # Grant gold
                        if rewards.get('gold'):
                            player_state['coins'] = player_state.get('coins', 0) + rewards['gold']
                        
                        # Grant items
                        if rewards.get('items'):
                            inventory = player_state.setdefault('inventory', [])
                            for item_id in rewards['items']:
                                inventory.append(item_id)
                        
                        # Grant reputation
                        if rewards.get('reputation'):
                            rep = rewards['reputation']
                            if rep.get('actor'):
                                for actor_id, amount in rep['actor'].items():
                                    # This would need a reputation system
                                    pass
                        
                        # Notify client of updated inventory/coins
                        _emit_inventory_update(player_id, player_state)
        
        elif action_type == 'complete_purchase':
            # ONLY apply when purchase is actually complete
            price = action.get('price', 0)
            item_id = action.get('item_id')
            quantity = action.get('quantity', 1)  # Get quantity, default to 1
            
            print(f"[COMPLETE_PURCHASE] price={price}, item_id={item_id}, quantity={quantity}")
            print(f"[COMPLETE_PURCHASE] Before: coins={player_state.get('coins')}, inventory={player_state.get('inventory')}")
            
            if price and item_id:
                player_state['coins'] = player_state.get('coins', 0) - price
                
                # Add item to inventory with correct quantity
                inventory = player_state.setdefault('inventory', [])
                already_has = False
                for entry in inventory:
                    if isinstance(entry, dict) and entry.get('item_id') == item_id:
                        entry['quantity'] = entry.get('quantity', 1) + quantity
                        already_has = True
                        break
                
                if not already_has:
                    inventory.append({'item_id': item_id, 'quantity': quantity})
            
            print(f"[COMPLETE_PURCHASE] After: coins={player_state.get('coins')}, inventory={player_state.get('inventory')}")
        
        # NOTE: prepare_purchase is NOT applied here - it's just an offer


def _check_childish_behavior(message: str) -> float:
    """Check if player is being childish (0-1 score) - Layer 1 utility"""
    childish_patterns = [
        r'(asdf|fghj|jkl|lol|lmao|rofl)',
        r'(ha{2,}|he{2,}|hi{2,})',
        r'(stupid|dumb|poop|fart)',
        r'(yo mama|your mom)',
        r'(nonsense|bla{2,})',
        r'(!{3,}|\?{3,}|lalala|nyah)',
    ]
    
    score = 0
    message_lower = message.lower()
    
    for pattern in childish_patterns:
        if re.search(pattern, message_lower):
            score += 0.3
    
    # Check for very short meaningless messages
    if len(message) < 3:
        score += 0.2
    
    return min(1.0, score)


def _apply_world_updates(world_updates: List[Dict], player_state: Dict, player_id: str):
    """Apply world state updates from simulation packet."""
    for update in world_updates:
        update_type = update.get('type', '')
        
        if update_type == 'coins_change':
            amount = update.get('amount', 0)
            player_state['coins'] = player_state.get('coins', 0) + amount
            
            # Emit inventory update to player
            _emit_inventory_update(player_id, player_state)
        
        elif update_type == 'inventory_add':
            item_id = update.get('item_id', '')
            quantity = update.get('quantity', 1)
            
            inventory = player_state.setdefault('inventory', [])
            
            # Check if item already in inventory
            already_has = False
            for entry in inventory:
                if isinstance(entry, dict) and entry.get('item_id') == item_id:
                    entry['quantity'] = entry.get('quantity', 1) + quantity
                    already_has = True
                    break
            
            if not already_has:
                inventory.append({'item_id': item_id, 'quantity': quantity})
            
            _emit_inventory_update(player_id, player_state)
        
        elif update_type == 'hp_change':
            amount = update.get('amount', 0)
            player_state['hp'] = player_state.get('hp', 0) + amount
        
        elif update_type == 'quest_complete':
            quest_id = update.get('quest_id', '')
            completed_quests = player_state.setdefault('completed_quests', [])
            if quest_id and quest_id not in completed_quests:
                completed_quests.append(quest_id)
            
            # Remove from active quests
            active_quests = player_state.get('quests', [])
            player_state['quests'] = [q for q in active_quests if q.get('id') != quest_id]


def _apply_memory_updates(memory_updates: Dict, player_id: str, npc_id: str,
                          conversation_memory: Dict, player_text: str):
    """Apply conversation memory updates from simulation packet."""
    if not memory_updates:
        return
    
    # Initialize memory structure if needed
    if player_id not in conversation_memories:
        conversation_memories[player_id] = {}
    if npc_id not in conversation_memories[player_id]:
        conversation_memories[player_id][npc_id] = {
            'history': [], 'state': 'general', 'childish_warnings': 0
        }
    
    mem = conversation_memories[player_id][npc_id]
    
    # Apply updates
    if memory_updates.get('initialized'):
        mem['history'] = memory_updates.get('history', [])
        mem['state'] = memory_updates.get('state', 'general')
        mem['childish_warnings'] = memory_updates.get('childish_warnings', 0)
    
    if 'childish_warnings' in memory_updates:
        mem['childish_warnings'] = memory_updates['childish_warnings']
    
    if 'state' in memory_updates:
        mem['state'] = memory_updates['state']
    
    if memory_updates.get('history_append'):
        mem['history'].append(memory_updates['history_append'])


def _execute_heal(player_state: Dict, npc_data: Dict) -> Dict:
    """Execute heal action."""
    from commands.core.heal_cmd import handle_heal
    from server.state import ACTOR_POSITIONS, get_actors_at_position
    
    player_id = player_state.get('id', '')
    player_pos = ACTOR_POSITIONS.get(player_id, {})
    actors_here = get_actors_at_position(player_pos.get('map_id'), player_pos.get('node_id'))
    
    # Get combat engine if available
    combat_engine = None
    if hasattr(socketio, 'combat_engine'):
        combat_engine = socketio.combat_engine
    
    heal_result = handle_heal(player_state, player_pos, actors_here, combat_engine)
    
    return heal_result




def _emit_inventory_update(player_id: str, player_state: Dict):
    """Emit inventory update to player."""
    equipment = player_state.get('equipment', {})
    item_list = []
    
    for entry in player_state.get('inventory', []):
        if isinstance(entry, dict) and 'item_id' in entry:
            eid = entry['item_id']
            qty = entry.get('quantity', 1)
            from engine.items import get_item_name, is_stackable
            item_display = get_item_name(eid)
            if is_stackable(eid) and qty > 1:
                item_list.append(f"{item_display} (x{qty})")
            else:
                item_list.append(item_display)
        else:
            item_display = entry.get('name', entry) if isinstance(entry, dict) else entry
            item_list.append(item_display)
    
    for slot, entry in equipment.items():
        if entry:
            item_display = entry.get('name', entry) if isinstance(entry, dict) else entry
            item_list.append(f"{item_display} (equipped {slot.replace('_', ' ')})")
    
    for sid, pid in player_sessions.items():
        if pid == player_id and socketio:
            socketio.emit('inventory_data', {
                'items': item_list,
                'coins': player_state.get('coins', 0)
            }, room=sid)
            break


def _detect_emotion(message: str) -> str:
    """Detect player emotion from message (Layer 1 utility)."""
    message_lower = message.lower()
    
    # Positive emotions
    if any(w in message_lower for w in ['thank', 'thanks', 'grateful', 'happy', 'glad', 'wonderful', 'great', 'awesome']):
        return 'positive'
    
    # Negative emotions
    if any(w in message_lower for w in ['angry', 'mad', 'furious', 'hate', 'stupid', 'dumb', 'idiot']):
        return 'negative'
    
    # Fear/anxiety
    if any(w in message_lower for w in ['scared', 'afraid', 'help', 'danger', 'fear']):
        return 'fearful'
    
    # Curiosity
    if any(w in message_lower for w in ['what', 'how', 'why', 'tell me', 'explain', 'curious']):
        return 'curious'
    
    # Urgency
    if any(w in message_lower for w in ['urgent', 'quickly', 'hurry', 'emergency', 'now']):
        return 'urgent'
    
    return 'neutral'


def _detect_attitude(message: str) -> str:
    """Detect player attitude from message (Layer 1 utility)."""
    message_lower = message.lower()
    
    # Friendly/cooperative
    if any(w in message_lower for w in ['please', 'help', 'assist', 'please', 'kind', 'grateful']):
        return 'friendly'
    
    # Aggressive/hostile
    if any(w in message_lower for w in ['attack', 'fight', 'kill', 'die', 'threat', 'intimidate']):
        return 'aggressive'
    
    # Demanding
    if any(w in message_lower for w in ['give me', 'i want', 'i need', 'must', 'now']):
        return 'demanding'
    
    # Curious/inquisitive
    if any(w in message_lower for w in ['what', 'how', 'why', 'tell me', 'explain', 'wonder']):
        return 'curious'
    
    # Rude/disrespectful
    if any(w in message_lower for w in ['stupid', 'dumb', 'idiot', 'shut up', 'whatever']):
        return 'rude'
    
    return 'neutral'


def _detect_seriousness(message: str) -> str:
    """Detect message seriousness (Layer 1 utility)."""
    message_lower = message.lower()
    
    # Very serious (all caps, exclamation marks, urgent keywords)
    if message.isupper() or message.count('!') > 2:
        return 'high'
    
    if any(w in message_lower for w in ['urgent', 'emergency', 'critical', 'important', 'serious']):
        return 'high'
    
    # Casual (lol, haha, informal language)
    if any(w in message_lower for w in ['lol', 'haha', 'hehe', 'lmao', 'rofl', 'jk', 'just kidding']):
        return 'low'
    
    # Medium seriousness (normal conversation)
    return 'medium'


def _append_to_history(player_id: str, npc_id: str, player_text: str, npc_response: str):
    """Append exchange to conversation history."""
    if player_id not in conversation_memories:
        conversation_memories[player_id] = {}
    if npc_id not in conversation_memories[player_id]:
        conversation_memories[player_id][npc_id] = {
            'history': [], 'state': 'general', 'childish_warnings': 0
        }
    
    mem = conversation_memories[player_id][npc_id]
    # Clean response - remove any wrapping quotes or brackets
    clean_response = npc_response.strip()
    if clean_response.startswith('"') and clean_response.endswith('"'):
        clean_response = clean_response[1:-1]
    if clean_response.startswith('[') and clean_response.endswith(']'):
        clean_response = clean_response[1:-1]
    
    mem['history'].append({'speaker': 'player', 'text': player_text})
    mem['history'].append({'speaker': 'npc', 'text': clean_response})
